- .gitignore
- Cargo.lock
- README.md
- rust/Cargo.toml
- solana-geyser-grpc/Cargo.toml
- solana-geyser-grpc/config.json
Small fix of https://github.com/rpcpool/solana-geyser-grpc/pull/62
> Remove not required dependencies from Cargo.toml

- .github/workflows/release.yml
- ci/cargo-install-all.sh
Fixes up the workflows for releases.
> Fix workflows for release

- Cargo.lock
- rust/Cargo.toml
- rust/client/client.rs
to make local test convenient:
if x-token is empty, will show a warning message.
if x-token is not empty, will check XTOKEN_LENGTH == 28.
> fix: x-token in client is optional

- Cargo.lock
- rust/Cargo.toml
- rust/client/client.rs
- solana-geyser-grpc/Cargo.toml
based on Linus commit: https://github.com/rpcpool/solana-geyser-grpc/commit/055cbf75448dd45352531be6a93fe8c9263025d0
> rust client: add resubscribe example

- Cargo.lock
- README.md
- examples/rust/Cargo.toml
- examples/rust/src/bin/client.rs
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/src/filters.rs
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-proto/proto/geyser.proto
> add memcmp/datasize filter to accounts

- Cargo.lock
- yellowstone-grpc-client/src/lib.rs
> Make clippy happy

- examples/rust/src/bin/client.rs
- yellowstone-grpc-client/src/lib.rs
- yellowstone-grpc-geyser/src/filters.rs
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-geyser/src/plugin.rs
- yellowstone-grpc-geyser/tests/test_filters.rs
- yellowstone-grpc-proto/proto/geyser.proto
> grpc, proto: add commitment level

- examples/rust/src/bin/client.rs
- yellowstone-grpc-client/src/lib.rs
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-proto/proto/geyser.proto
Closes #123 
Replace #129 (this support commitment)
> grpc, proto: add unary is_blockhash_valid

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/src/bin/client.rs
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/config.json
- yellowstone-grpc-geyser/src/config.rs
- yellowstone-grpc-geyser/src/grpc.rs
> geyser: allow to disable unary methods

- CHANGELOG.md
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-geyser/src/plugin.rs
> geyser: use Notify instead of AtomicBool in send loop

- Cargo.lock
- examples/rust/Cargo.toml
- examples/rust/src/bin/tx-blocktime.rs
> examples: add rust transactions blocktime

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- yellowstone-grpc-client-nodejs/package.json
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/src/plugin.rs
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-tools/Cargo.toml
> geyser: remove startup_status

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-tools/Cargo.toml
- yellowstone-grpc-tools/src/config.rs
features in tools extracted from #239
> use workspace for dependencies

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- examples/rust/Cargo.toml
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-tools/Cargo.toml
Backport of https://github.com/rpcpool/yellowstone-grpc/pull/245
> v1.16: geyser: reconstruct blocks with zero entries (backport of #245)

- yellowstone-grpc-tools/config-kafka.json
- yellowstone-grpc-tools/src/bin/grpc-google-pubsub.rs
- yellowstone-grpc-tools/src/bin/grpc-kafka.rs
- yellowstone-grpc-tools/src/config.rs
- yellowstone-grpc-tools/src/lib.rs
> tools: add setup_tracing

- CHANGELOG.md
- yellowstone-grpc-geyser/src/plugin.rs
```
$ nc -U test-ledger/admin.rpc
[{"method":"listPlugins","jsonrpc":"2.0","params":[],"id":"1"}]
[{"jsonrpc":"2.0","result":["yellowstone-grpc-geyser-1.11.1+solana.1.17.6"],"id":"1"}]
```
> geyser: change plugin name to `{name}-{version}`

- examples/rust/src/bin/client.rs
> examples: allow to load accounts from file

- CHANGELOG.md
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-geyser/src/plugin.rs
- yellowstone-grpc-geyser/src/prom.rs
> geyser: add metric `slot_status_plugin`

- CHANGELOG.md
- yellowstone-grpc-geyser/src/grpc.rs
Tokio docs: https://docs.rs/tokio/latest/tokio/task/index.html#cooperative-scheduling
> geyser: mark `geyser_loop` as unconstrained

- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-tools/Cargo.toml
upgrade to latest solana version.
> solana: v1.18.11 upgrade

- yellowstone-grpc-geyser/src/config.rs
- yellowstone-grpc-geyser/src/grpc.rs
feat: add optional x_token check in grpc server
> feat: add optional x_token check in grpc server

- examples/golang/go.mod
https://github.com/rpcpool/yellowstone-grpc/issues/363
> Fix module path

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deny.toml
- examples/rust/Cargo.toml
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-tools/Cargo.toml
Moved from https://github.com/rpcpool/yellowstone-grpc/pull/366
> solana: update to 1.18.17

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- examples/rust/src/bin/client.rs
- examples/rust/src/bin/subscribe-ping.rs
- examples/rust/src/bin/tx-blocktime.rs
> example: fix tls root issue in rust example

- CHANGELOG.md
- yellowstone-grpc-geyser/src/grpc.rs
Improved version of https://github.com/rpcpool/yellowstone-grpc/pull/435
> geyser: optimize consuming of new filters

- CHANGELOG.md
- Cargo.lock
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/config.json
- yellowstone-grpc-geyser/src/config.rs
- yellowstone-grpc-geyser/src/filters.rs
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-proto/src/lib.rs
- yellowstone-grpc-proto/src/plugin/filter.rs
- yellowstone-grpc-proto/src/plugin/mod.rs
> proto: add mod `plugin` with `FilterNames` cache

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/config.json
- yellowstone-grpc-geyser/src/config.rs
- yellowstone-grpc-geyser/src/grpc.rs
Closes https://github.com/rpcpool/yellowstone-grpc/issues/495
> geyser: fix `replay_stored_slots`

- yellowstone-grpc-proto/proto/fumarole.proto
DeleteConsumerGroup gRPC endpoint
> fumarole: added ListConsumerGroups,DeleteConsumerGroup and

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- yellowstone-grpc-client-nodejs/solana-encoding-wasm/Cargo.lock
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-proto/src/plugin/filter/filter.rs
> geyser: runtime error on invalid commitment

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rust/Cargo.toml
- examples/typescript/package-lock.json
- examples/typescript/package.json
- yellowstone-grpc-client-nodejs/package-lock.json
- yellowstone-grpc-client-nodejs/package.json
- yellowstone-grpc-client-nodejs/solana-encoding-wasm/Cargo.lock
- yellowstone-grpc-client-nodejs/solana-encoding-wasm/Cargo.toml
- yellowstone-grpc-client/Cargo.toml
- yellowstone-grpc-geyser/Cargo.toml
- yellowstone-grpc-geyser/src/grpc.rs
- yellowstone-grpc-geyser/src/metrics.rs
- yellowstone-grpc-proto/Cargo.toml
- yellowstone-grpc-proto/proto/geyser.proto
- yellowstone-grpc-proto/src/plugin/filter/filter.rs
- yellowstone-grpc-proto/src/plugin/filter/message.rs
- yellowstone-grpc-proto/src/plugin/message.rs
Update of #525 
https://github.com/rpcpool/yellowstone-grpc/pull/525#discussion_r1943483499
> proto: add enum `SlotStatus`
