rpcpool/yellowstone-grpc

.github/workflows/release.yml
.github/workflows/test.yml

Since the repo is public, we switch over to GH's runners for now.

Switch to Github's runners

---

examples/rust/src/bin/client.rs
yellowstone-grpc-client/src/lib.rs

add ping,get_latest_blockhash,get_block_height,get_slot for yellowstone-grpc-client

rust client: add unary methods

---

yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/lib.rs

Previously connection would be removed from `HashMap` only on filter match and already disconnected client. With this patch, the connection would be removed immediately after disconnecting.

plugin: remove connection after disconnect

---

README.md
examples/rust/src/bin/client.rs
yellowstone-grpc-client/src/lib.rs
yellowstone-grpc-geyser/build.rs
yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/prom.rs
yellowstone-grpc-geyser/src/version.rs
yellowstone-grpc-proto/proto/geyser.proto

Based on #128 
Closes #47 
Return version as string:
```
[2023-05-24T20:11:32Z INFO  client] response: GetVersionResponse { version: "{\"version\":\"0.6.1+solana.1.15.2\",\"solana\":\"1.15.2\",\"git\":\"41d1bad-modified\",\"rustc\":\"1.66.1\",\"buildts\":\"2023-05-24T19:39:04.796311939Z\"}" }
```

grpc, proto: add getVersion

---

CHANGELOG.md
Cargo.lock
Cargo.toml
yellowstone-grpc-geyser/Cargo.toml
yellowstone-grpc-geyser/config.json
yellowstone-grpc-geyser/src/config.rs
yellowstone-grpc-geyser/src/filters.rs

geyser: fix config example

---

yellowstone-grpc-geyser/src/config.rs
yellowstone-grpc-geyser/src/grpc.rs

Add `tls_config` to `ConfigGrpc` so that you can specify cert/key path required to enable TLS

geyser: Add TLS config to gRPC server

---

CHANGELOG.md
yellowstone-grpc-geyser/Cargo.toml

Currently with newer versions of tokio does not compile because it requires feauture flag fs enabled in Cargo.toml

adding fs in tokio features to support fs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/rust/Cargo.toml
examples/rust/src/bin/tx-blocktime.rs
yellowstone-grpc-client/Cargo.toml
yellowstone-grpc-geyser/Cargo.toml
yellowstone-grpc-kafka/Cargo.toml
yellowstone-grpc-proto/Cargo.toml

Use gRPC 1.16.1 with validator 1.16.14 produce incorrect `failed` status.
https://docs.rs/solana-sdk/1.16.1/solana_sdk/transaction/enum.TransactionError.html
vs
https://docs.rs/solana-sdk/1.16.14/solana_sdk/transaction/enum.TransactionError.html
35 variants vs 36, as result deserialization is not correct

geyser: update solana =1.16.14

---

CHANGELOG.md
Cargo.lock
yellowstone-grpc-tools/Cargo.toml
yellowstone-grpc-tools/src/bin/grpc-kafka.rs
yellowstone-grpc-tools/src/kafka/prom.rs

tools: correctly handle SIGINT in kafka

---

Cargo.lock
yellowstone-grpc-tools/Cargo.toml

building the _rdkafka_ crate fails on mac per default configuration
>   _mkltmpuU0ERk.c:2:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
^~~~~~~~~~~~~~~
1 error generated.
see https://github.com/fede1024/rust-rdkafka/issues/491
ssl -> ssl-vendored

fixes openssl link problem (on mac os)

---

examples/rust/src/bin/client.rs
yellowstone-grpc-client/src/lib.rs

Some load balancers (eg. Cloudflare) expect a message to come through before passing a gRPC connection through to origin. Because the current subscribe method connects, and then sends a message, it causes a delay when connecting. This pr adds `subscribe_with_request` which pushes a request into the channel before sending the subscribe request. This resolves the LB issue

fix(client): Include request in initial subscribe to gRPC endpoint to fix LB connection delay

---

Cargo.toml
LICENSE
LICENSING.md
examples/LICENSE_APACHE2
examples/rust/Cargo.toml
yellowstone-grpc-client-nodejs/LICENSE_APACHE2
yellowstone-grpc-client/Cargo.toml
yellowstone-grpc-client/LICENSE_APACHE2
yellowstone-grpc-proto/Cargo.toml
yellowstone-grpc-proto/LICENSE_APACHE2

This PR relicenses this repo as AGPL and makes all further contributions to this repo fall under AGPL. Client libraries and protobuf proto files will continue to be licensed under the Apache license.
**Motivation**
We want to make sure that this gRPC interface gets utilised in a standardised way across the Solana ecosystem. It is important that any user that builds against this gRPC interface has a choice of many compatible providers to use. Therefore we desire that anyone who seeks to provide a hosted version of this gRPC interface to downstream users should also make their modifications to the gRPC interface open source so they can be adopted by other users of this plugin.
Client libraries and proto files remain under the Apache license. This means that anyone building this into their …

Relicensing as AGPL

---

yellowstone-grpc-client-nodejs/package.json

Solves this error
```
$:~/workspace/triton/yellowstone-grpc/yellowstone-grpc-client-nodejs$ npm run build
> @triton-one/yellowstone-grpc@0.3.0 build
> npm run grpc-generate && tsc -p .
> @triton-one/yellowstone-grpc@0.3.0 grpc-generate
> protoc -I../yellowstone-grpc-proto/proto --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=forceLong=string --ts_proto_opt=outputServices=grpc-js --ts_proto_out=./src/grpc geyser.proto
geyser.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
i@i:~/workspace/triton/yellowstone-grpc/yellowstone-grpc-client-nodejs$ cd ../examples/typescript/
```
```
protoc --version
libprotoc 3.12.4
```

add flag to enable proto3 optional fields

---

CHANGELOG.md
yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/plugin.rs

We need to clone messages for every connected client (even if they subscribe only on slots we will copy all accounts/transactions messages), wrap messages to Arc should help

geyser: wrap messages to `Arc`

---

CHANGELOG.md
yellowstone-grpc-geyser/src/grpc.rs

geyser: fix getLatestBlockhash unary method

---

CHANGELOG.md
yellowstone-grpc-geyser/src/filters.rs
yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/prom.rs

```
subscritpions_total{subscription="accounts"} 0
subscritpions_total{subscription="all"} 2
subscritpions_total{subscription="blocks"} 0
subscritpions_total{subscription="blocks_meta"} 1
subscritpions_total{subscription="entry"} 0
subscritpions_total{subscription="grpc_total"} 1
subscritpions_total{subscription="slots"} 1
subscritpions_total{subscription="transactions"} 0
subscritpions_total{subscription="transactions_status"} 0
```

geyser: add metric `subscriptions_total`

---

Cargo.toml
examples/rust/Cargo.toml
yellowstone-grpc-geyser/Cargo.toml
yellowstone-grpc-proto/Cargo.toml
yellowstone-grpc-proto/src/lib.rs

- Do to the recent version plucking in 2.x of Solana crates.
- Add `convert` feature to exclude some solana crates but they are still included by default.
```
error: failed to select a version for `solana-account-decoder`.
... required by package `yellowstone-grpc-proto v1.14.0`
... which satisfies dependency `yellowstone-grpc-proto = "^1.14.0"` of package `yellowstone-vixen v0.0.0 (/Users/kyleespinola/Code/rpcpool/yellowstone-vixen/crates/runtime)`
versions that meet the requirements `>=1.17.28, <1.18.0` are: 1.17.34, 1.17.33, 1.17.32, 1.17.31, 1.17.30, 1.17.29, 1.17.28
all possible versions conflict with previously selected packages.
previously selected package `solana-zk-token-sdk v2.0.0`
... which satisfies dependency `solana-zk-token-sdk = "^2.0.0"` of package `spl-token-2022 v4.0.1` …
```

Optional solana crates

---

yellowstone-grpc-client-nodejs/src/index.ts

Updated nodejs client to allow `x-token` to be passed also without TLS

feat(node-client): allow xtoken for http connections

---

CHANGELOG.md
yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/plugin.rs

- wrap message into `Box`
- drop `Sender` on end of startup

geyser: wrap message into `Box` in snapshot channel

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/rust/Cargo.toml
yellowstone-grpc-client/Cargo.toml
yellowstone-grpc-geyser/Cargo.toml
yellowstone-grpc-proto/Cargo.toml

Bump version for crates.io. We can not publish with solana change `~1.18`  -> `~2.0` without doing a major version bump in gRPC crates.

version: bump

---

CHANGELOG.md
examples/golang/README.md
examples/python/README.md
examples/typescript/README.md
examples/typescript/src/client.ts

examples: fix commitment in TypeScript example

---

.github/workflows/test.yml
CHANGELOG.md
Cargo.lock
yellowstone-grpc-geyser/config.json
yellowstone-grpc-geyser/src/config.rs
yellowstone-grpc-geyser/src/filters.rs
yellowstone-grpc-geyser/src/grpc.rs
yellowstone-grpc-geyser/src/lib.rs
yellowstone-grpc-geyser/src/metrics.rs
yellowstone-grpc-geyser/src/plugin.rs
yellowstone-grpc-proto/Cargo.toml
yellowstone-grpc-proto/src/plugin/message.rs
yellowstone-grpc-proto/src/plugin/mod.rs

moved from https://github.com/rpcpool/yellowstone-grpc/pull/449

proto: move enum Message from geyser crate

---

CHANGELOG.md
examples/rust/src/bin/client.rs

The configuration file of the geyser plugin allows the addition of certificates but it is not currently possible to add a root authority in the Rust client.
https://github.com/rpcpool/yellowstone-grpc/blob/3192b5508d91b342a7e2a714df088efc72598558/yellowstone-grpc-geyser/config.json#L12-L15
For example, with the newly introduced parameter it is now possible to interact with self-made CAs.

geyser: Add option to allow the injection of a root authority

---

README.md

Hi guys,  
I've corrected the following:  
- **"acount Pubkey"** → changed to **"account Pubkey"**  
- **"as workaroud"** → changed to **"as workaround"**  
- **"fields works as logical AND"** → changed to **"fields work as logical AND"**  
- **"filters doesn't have any limits"** → changed to **"filters don't have any limits"**  
These updates should make the documentation more precise and professional.

docs: Fix Typos in Doc Update README.md

---

CHANGELOG.md
examples/typescript/package-lock.json
examples/typescript/tsconfig.json
yellowstone-grpc-client-nodejs/add-js-extensions.js
yellowstone-grpc-client-nodejs/package-lock.json
yellowstone-grpc-client-nodejs/package.json
yellowstone-grpc-client-nodejs/src/index.ts
yellowstone-grpc-client-nodejs/tsconfig.cjs.json
yellowstone-grpc-client-nodejs/tsconfig.esm.json
yellowstone-grpc-client-nodejs/tsconfig.json

- use --ts_proto_opt=esModuleInterop=true arg when generating with proto
- split esm / cjs into 2 seperate tsconfigs
- add npm run command to copy compiled encoding folder contents to esm/cjs
- add script to fix the imports in the ESM version
Tested with CJS / ESM / TS enviroments for Subsrbribing to transactions for a program account
"esModuleInterop": true is required in projects tsconfig.json compilerOptions

add support for utilizing npm package in ESM environments

---

CHANGELOG.md
Cargo.lock
Cargo.toml
yellowstone-grpc-client/Cargo.toml
yellowstone-grpc-client/src/lib.rs

I am getting:
```
Error: tonic::transport::Error(Transport, ConnectError(HttpsUriWithoutTlsSupport(())))
```
When using the latest gRPC client against an https endpoint. To fix this I need to specify a ClientTLSConfig, but I cannot because it's not exposed as part of the yellowstone-grpc-client.
Relevant issue:
https://github.com/hyperium/tonic/issues/1817
Note:
For some reason, I do not get this error when using the 1.15 client. Only 2.0.0 and above.

Expose TLS Config as part of the client

---

CHANGELOG.md
Cargo.lock
Cargo.toml
yellowstone-grpc-geyser/Cargo.toml
yellowstone-grpc-geyser/src/config.rs

The param `replay_stored_slots` is of type `u64`. This PR adds a string to u64 deserializer to it.
fixes #542

geyser: string to u64 dserializer

---

yellowstone-grpc-client-nodejs/package.json

as discussed here https://github.com/rpcpool/yellowstone-grpc/issues/555
and originally pointed out here: https://github.com/rpcpool/yellowstone-grpc/pull/537
adding types to the exports seems to help with esm compatability in some environments. Tested with the client and local esm project and seems safe, no obvious issues.

tweaks to package.json to improve esm support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/rust/Cargo.toml
examples/rust/src/bin/client.rs

In the Rust example, subscribing to slot updates sometimes misses updates with certain commitment levels.  This leads to errors and unnecessary reconnections, a process that repeats continuously. This issue should be fixed.

fix: Slot update message now handles levels missing from CommitmentLevel

---

Cargo.lock
yellowstone-grpc-geyser/src/grpc.rs

This PR fixes an edge case in account update deduplication for `slot_messages.messages`.
Yellowstone gRPC saves account updates into `slot_messages.messages`.
The intent is to keep only the latest (highest `write_version`) account update per pubkey within a slot.
Deduplication is tracked via `slot_messages.accounts_dedup`.
Previously, when an account update arrived out of order (with a `write_version` **lower** than the highest seen so far), the code failed to discard it.
Because messages are appended to `slot_messages.messages` **before** deduplication logic runs, this resulted in multiple updates being saved for the same pubkey in a slot.
Added an else branch to handle the case where the new update’s `write_version` is lower than the latest one.
The new (out-of-order) message is …

fix(slot_messages): handle lower write_version by dropping messages

---

.github/workflows/release.yml

Right now ubuntu24 builds are getting named without ubuntu versions suffix (naming used by ubuntu20 builds)
make it generic so it will add version to any ubuntu version in use

update renaming task in release workflow
